global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "aws-lambda"
    static_configs:
      - targets: ["localhost:3000"]
  - job_name: "aws-glue"
    static_configs:
      - targets: ["localhost:9091"]
  - job_name: "kinesis-stream"
    static_configs:
      - targets: ["localhost:9092"]

